config/routes.rb
Remotehue::Application.routes.draw do
  resources :sessions, :only => :new

  get "/ping" => "internal#ping"
  get "/internal/state" => "internal#state"

  scope :module => :api, :as => :api, :path => "/api/v1" do
    controller :mailgun, :as => :mailgun, :path => "/mailgun/:secret" do
      post "/" => :trigger
    end

    controller :trigger, :as => :trigger, :path => "/trigger" do
      post "/:user_id/:trigger_id" => :activate, :as => :activate
    end
  end

  controller :sessions, :path => :sessions, :as => :session do
    get "/logout" => :destroy, :as => :logout
    get "/:provider/callback" => :create
    get "/failure" => :failure
  end

  resources :faq, :only => :index
  resource :subscription, :path => "/subscriptions", :only => :show

  resource :fastspring, :path => "/fastspring/:secret" do
    post "/sub/activated" => :sub_activated
    post "/sub/canceled" => :sub_canceled
    post "/sub/changed" => :sub_changed
    post "/sub/failed" => :sub_failed
    post "/sub/refund" => :sub_refund
    post "/order/notification" => :order_notification
  end

  scope :module => :usercp, :as => :usercp, :path => "" do
    controller :help, :path => :help, :as => :help do
      get "/meethue" => :meethue
      get "/ifttt/:trigger_id" => :ifttt, :as => :ifttt
    end

    resources :bridges do
      collection do
        post "/meethue-login" => :meethue_login, :as => :meethue_login
      end

      member do
        put "/resync" => :resync, :as => :resync
        put "/meethue-login" => :meethue_check, :as => :meethue_check
        put "/update-software" => :update_software, :as => :update_software
        get "/confirm-delete" => :confirm_destroy, :as => :confirm_destroy
      end
    end

    resources :triggers do
      member do
        get "/history" => :history, :as => :history
        get "/usage" => :usage, :as => :usage
        post "/regenerate" => :regenerate, :as => :regenerate
      end
    end

    resources :schedules do
      member do
        get "/usage" => :usage, :as => :usage
        get "/history" => :history, :as => :history
      end
    end

    resources :scenes
    resource :setting do
      member do
        put "/inline-location" => :inline_location, :as => :inline_location
        post "/solar" => :solar_events, :as => :solar_events
      end
    end

    resource :billing
  end

  get "/privacy-policy" => "home#privacy_policy", :as => :privacy_policy
  get "/terms-of-service" => "home#terms_conditions", :as => :terms_conditions
  get "/" => "home#show", :as => :root

  unless Rails.env.production?
    match "/404" => "error#routing"
  end
end

app/controllers/usercp/base_controller.rb
class Usercp::BaseController < ApplicationController
  before_filter :require_logged_in

  def respond_with_model(model, status=:ok)
     if model.errors.empty?
       render :json => {:id => model._id}, :status => status
     else
       data = {:errors => {}.merge(model.errors.messages), :attributes => {}, :scope => model.class.collection_name.singularize}
       data[:errors].each_key {|e| data[:attributes][e] = model.class.human_attribute_name(e)}

       # Check for children
       data[:errors].merge!(load_model_errors(model, data[:attributes]))

       render :json => data, :status => :bad_request
     end
  end

  def load_model_errors(model, attrib_scope)
    errors = {}

    model.associations.each do |key, assoc|
      next unless assoc.embeddable? and model.errors[key]
      embedded = model.send(key)
      next unless embedded

      errors[key] = {}

      # Multiple embedded
      if assoc.is_a?(MongoMapper::Plugins::Associations::ManyAssociation)
        embedded.each do |child|
          next if child.errors.empty?

          errors[key][child._id] = {}.merge(child.errors.messages)
          errors[key][child._id].each_value {|v| v.uniq!}
          errors[key][child._id].each_key {|e| attrib_scope[e] = assoc.klass.human_attribute_name(e)}
          errors[key][child._id].merge!(load_model_errors(child, attrib_scope))
        end

      # Single embedded, merge any errors
      else
        errors[key].merge!(embedded.errors.messages)
        errors[key].each_value {|v| v.uniq!}
        errors[key].each_key {|e| attrib_scope[e] = assoc.klass.human_attribute_name(e)}

        errors[key].merge!(load_model_errors(embedded, attrib_scope))
      end

      if errors[key].empty?
        errors.delete(key)
        next
      end
    end

    errors
  end
end

app/controllers/usercp/billing_controller.rb
class Usercp::BillingController < Usercp::BaseController
  def index

  end
end

app/controllers/usercp/bridges_controller.rb
class Usercp::BridgesController < Usercp::BaseController
  def new
    @bridge = Bridge.new
    @bridge.api_key = Digest::SHA1.hexdigest("#{current_user._id}#{CONFIG[:bridge_secret]}#{current_user.created_at}")

    render :manage
  end

  def edit
    @bridge = Bridge.where(:_id => params[:id].to_s, :user_id => current_user._id).first
    return render_404 unless @bridge

    render :manage
  end

  def update
    bridge = Bridge.where(:_id => params[:id].to_s, :user_id => current_user._id).first
    return render_404 unless bridge

    bridge.api_key = params[:api_key].to_s
    bridge.local_ip = params[:ip].to_s
    bridge.save

    respond_with_model(bridge)
  end

  def resync
    bridge = Bridge.where(:_id => params[:id].to_s, :user_id => current_user._id).first
    return render_404 unless bridge

    unless bridge.manually_resynced?
      bridge.load_data
      bridge.save

      bridge.set(:manually_resynced => true)

      flash[:success] = t("usercp.bridges.index.bridge_resynced", :name => bridge.name)
    end

    render :nothing => true, :status => :no_content
  end

  def meethue_check
    bridge = Bridge.where(:_id => params[:id].to_s, :user_id => current_user._id).first
    return render_404 unless bridge

    bridge.load_data
    bridge.save
    flash[:success] = t("usercp.bridges.manage.bridge_saved", :name => bridge.name) if bridge.errors.empty?

    respond_with_model(bridge)
  end

  def meethue_login
    if params[:id]
      bridge = Bridge.where(:_id => params[:id].to_s, :user_id => current_user._id).first
      return render_404 unless bridge
    else
      bridge = Bridge.new
      bridge.user = current_user
      bridge.api_key = params[:api_key].to_s
      bridge.local_ip = params[:ip].to_s
    end

    email, password = params[:email].to_s.strip, params[:password].to_s.strip
    bridge_id = params[:bridge_id].to_s.strip
    if email.blank? or password.blank? or bridge_id !~ /\A[a-z0-9]+\z/
      return render_404
    end

    # Get our session
    res = Stats.network("meethue.gettoken") do
      Excon.get("https://www.meethue.com/en-US/api/gettoken?devicename=Remote+Hue&appid=hueapp&deviceid=#{bridge.api_key}", :headers => {"User-Agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.65 Safari/537.36"})
    end
    cookie = res.headers["Set-Cookie"]
    unless cookie.match(/PLAY_SESSION="(.+)"/)
      return render :json => {:error => "session"}, :status => :bad_request
    end

    # Login as the user
    last_url = "https://www.meethue.com/en-US/api/gettoken?devicename=Remote+Hue&appid=hueapp&deviceid=#{bridge.api_key}"
    res = Stats.network("meethue.getaccesstoken") do
      Excon.post("https://www.meethue.com/en-US/api/getaccesstokengivepermission", :headers => {"Content-Type" => "application/x-www-form-urlencoded; charset=UTF-8", "Cookie" => "PLAY_SESSION=\"#{$1}\"", "User-Agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.65 Safari/537.36", :"Referer" => last_url}, :body => {:email => email, :password => password}.to_query)
    end
    if res.status == 302
      if res.headers["Set-Cookie"] =~ /PLAY_FLASH="(.+)"/
        return render :json => {:error => $1 =~ /authentication/i ? "auth" : "unknown0"}, :status => :bad_request
      else
        return render :json => {:error => "unknown1"}, :status => :bad_request
      end

    elsif res.status != 200 or res.body !~ /requesting access/i
      return render :json => {:error => "unknown2"}, :status => :bad_request
    end

    # Get any updated session info
    cookie = res.headers["Set-Cookie"]
    unless cookie.match(/PLAY_SESSION="(.+)"/)
      return render :json => {:error => "session"}, :status => :bad_request
    end

    # Now do the last bit of confirmation that we confirm
    last_url = "https://www.meethue.com/en-US/api/getaccesstokengivepermission"
    res = Stats.network("meethue.getaccesstokenpost") do
      Excon.get("https://www.meethue.com/en-US/api/getaccesstokenpost", :headers => {:"Content-Type" => "application/x-www-form-urlencoded; charset=UTF-8", "Cookie" => "PLAY_SESSION=\"#{$1}\"", :"Referer" => last_url, :"User-Agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.65 Safari/537.36"})
    end
    if res.status == 200
      if res.body =~ %r{phhueapp://sdk/login/([a-zA-Z0-9/=\+]+)}
        current_user.set(:pending_token => $1)

        bridge.bridge_id = bridge_id
        bridge.meethue_token = $1
        bridge.load_data
        bridge.next_update_at = Time.now.utc + rand(4).hours
        bridge.save

        current_user.unset(:pending_token)

        flash[:success] = t("usercp.bridges.manage.#{!params[:id] ? "bridge_created" : "bridge_saved"}", :name => bridge.name) if bridge.errors.empty?
        respond_with_model(bridge, :created)
      else
        return render :json => {:error => "unknown3"}, :status => :bad_request
      end
    else
      return render :json => {:error => "unknown4"}, :status => :bad_request
    end
  end

  def index
    @bridges = current_user.bridges.sort_by {|b| b.name}

  end

  def update_software

  end

  def confirm_destroy

  end

  private
end

app/controllers/usercp/help_controller.rb
class Usercp::HelpController < Usercp::BaseController
  def meethue

  end

  def ifttt
    @trigger = current_user.triggers.where(:_id => params[:trigger_id].to_s).first
    return render_404 unless @trigger
  end
end

app/controllers/usercp/scenes_controller.rb
class Usercp::ScenesController < Usercp::BaseController
  def index

  end
end

app/controllers/usercp/schedules_controller.rb
class Usercp::SchedulesController < Usercp::BaseController
  def index
    @schedules = current_user.schedules.sort_by {|t| t.name}
  end

  def new
    @schedule = Schedule.new
    @has_location = current_user.latitude? && current_user.longitude?

    render :manage
  end

  def create
    manage_schedule(Schedule.new(:user => current_user))
  end

  def history
    @schedule = current_user.schedules.where(:_id => params[:id].to_s).only(:name).first
    return render_404 unless @schedule

    @history = current_user.schedule_history.where(:schedule_id => @schedule._id).sort(:_id.desc).map {|h| h}
    render :layout => false
  end

  def edit
    @schedule = current_user.schedules.where(:_id => params[:id].to_s).first
    return render_404 unless @schedule
    @has_location = current_user.latitude? && current_user.longitude?

    render :manage
  end

  def update
    schedule = current_user.schedules.where(:_id => params[:id].to_s).first
    return render_404 unless schedule
    manage_schedule(schedule)
  end

  def destroy
    schedule = current_user.schedules.where(:_id => params[:id].to_s).first
    if schedule
      schedule.destroy
    end

    render :nothing => true, :status => :no_content
  end

  private
  def manage_schedule(schedule)
    schedule.name = params[:name].to_s
    schedule.enabled = params[:enabled] == "true"
    schedule.mode = case params[:type]
      when "sunset" then Schedule::SUNSET
      when "sunrise" then Schedule::SUNRISE
      else Schedule::TIME
    end
    schedule.days = []

    if params[:days].is_a?(Array)
      params[:days].each do |day|
        day = day.to_i

        schedule.days.push(day) if day >= 1 and day <= 7
      end
    end

    if params[:trigger_ids].is_a?(Array)
      ids = params[:trigger_ids].select {|id| BSON::ObjectId.legal?(id)}
      schedule.trigger_ids = current_user.triggers.where(:_id.in => ids).only(:_id).map do |trigger|
        trigger._id
      end

    else
      schedule.trigger_ids = []
    end

    schedule.run_unless = params[:run_unless].to_i

    if schedule.mode == Schedule::TIME
      schedule.run_hour = params[:run_hour].to_s.gsub(/[^\sapm0-9:]+/i, "")
    elsif schedule.mode == Schedule::SUNRISE
      schedule.sun_offset = params[:sun_offset].to_i
    elsif schedule.mode == Schedule::SUNSET
      schedule.sun_offset = params[:sun_offset].to_i
    end

    if schedule.valid?
      schedule.next_run_at = schedule.calc_next_run
    end
    schedule.save

    if schedule.errors.empty? and schedule.next_run_at <= 10.minutes.from_now.utc
      SchedulerDispatch.perform_async
    end

    if schedule.errors.empty?
      flash[:success] = t("usercp.schedules.manage.schedule_#{params[:action] == "create" ? "created" : "updated"}", :name => schedule.name)
    end

    respond_with_model(schedule)
  end
end

app/controllers/usercp/settings_controller.rb
class Usercp::SettingsController < Usercp::BaseController
  def index

  end

  def edit

  end

  def update
    user = User.where(:_id => current_user._id).first
    user.full_name = params[:full_name].to_s
    user.email = params[:email].to_s
    user.timezone = params[:timezone].to_s
    user.time_mode = params[:time_mode].to_i
    user.latitude = params[:latitude].to_f
    user.longitude = params[:longitude].to_f
    user.email_market = params[:email_market] != "false"

    if user.valid?
      flash[:success] = t("usercp.settings.edit.settings_updated")
    end

    user.save
    respond_with_model(user)
  end


  def inline_location
    current_user.latitude = params[:latitude].to_f
    current_user.longitude = params[:longitude].to_f
    current_user.save

    solar_events
  end

  def solar_events
    require Rails.root.join("lib", "solar_event")
    se = SolarEvent.new(Date.today, params[:latitude].to_f.to_d, params[:longitude].to_f.to_d)
    sunrise = se.send("compute_official_sunrise", current_user.timezone)
    sunset = se.send("compute_official_sunset", current_user.timezone)

    render :json => {:sunrise => current_user.formatted_hour(sunrise, false), :sunset => current_user.formatted_hour(sunset, false), :timezone => current_user.with_time_zone.zone}
  end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
  def solar_offset_options(type)
    list = []

    list.push([t("usercp.schedules.manage.before_#{type}_hour", :count => 3), -180])
    list.push([t("usercp.schedules.manage.before_#{type}_hour", :count => 2.5), -150])
    list.push([t("usercp.schedules.manage.before_#{type}_hour", :count => 2), -120])
    list.push([t("usercp.schedules.manage.before_#{type}_hour", :count => 1.5), -90])
    list.push([t("usercp.schedules.manage.before_#{type}_hour", :count => 1), -60])

    [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55].reverse.each do |min|
      list.push([t("usercp.schedules.manage.before_#{type}", :minutes => min), -min])
    end

    list.push([t("usercp.schedules.manage.at_#{type}"), 0])

    [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55].each do |min|
      list.push([t("usercp.schedules.manage.after_#{type}", :minutes => min), min])
    end

    list.push([t("usercp.schedules.manage.after_#{type}_hour", :count => 1), 60])
    list.push([t("usercp.schedules.manage.after_#{type}_hour", :count => 1.5), 90])
    list.push([t("usercp.schedules.manage.after_#{type}_hour", :count => 2), 120])
    list.push([t("usercp.schedules.manage.after_#{type}_hour", :count => 2.5), 150])
    list.push([t("usercp.schedules.manage.after_#{type}_hour", :count => 3), 180])

    # Convert minutes into seconds
    list.each {|t| t[1] = t[1] * 60}

    list
  end

  def trigger_list
    list = {}
    current_user.triggers.sort(:name.asc).only(:name, :_type).each do |trigger|
      list[t("trigger_types.#{trigger._type}")] ||= []
      list[t("trigger_types.#{trigger._type}")].push([trigger.name, trigger._id])
    end

    list
  end
end

app/views/usercp/schedules/history.html.haml
%table.table.table-hover.table-striped.table-bordered
  %thead
    %tr
      %th.center= t(".results")
      %th= t(".created_at")

  %tbody
    - if @history.empty?
      %tr
        %td{:colspan => 2}= t(".not_ran_yet", :name => @schedule.name)

    - else
      - @history.each do |row|
        %tr
          %td.center
            = t(".result_types.#{row.results}")
            %a.tt{"title" => t(".result_types_desc.#{row.results}"), :href => "#"} [?]
          %td= current_user.formatted_time(row.created_at)

:javascript
  $("#schedule-history .tt").tooltip();

app/views/usercp/schedules/index.html.haml
.row
  .span12
    %h3.header= t(".schedule_index")

- if @schedules.empty?
  .row
    .span12
      .alert.alert-block
        .close{"data-dismiss" => :alert} x
        %h4= t(".no_schedules_found")
        = linkify_text(t(".add_a_schedule"), new_usercp_schedule_path)

- else
  .row
    .span12
      %table.table.table-hover.table-striped.table-bordered
        %thead
          %tr
            %th= t(".name")
            %th.center= t(".type")
            %th.center= t(".days")
            %th.center= t(".next_run")
            %th.center= t(".history")
            %th.center= t(".edit")
            %th.center= t(".delete")

        %tbody
          - @schedules.each do |schedule|
            %tr
              %td
                - if schedule.enabled?
                  %span.text-success= schedule.name
                - else
                  %span.text-error= schedule.name

              %td.center= t(".time_types.#{schedule.mode}")
              %td.center
                - if schedule.days.length == 7
                  = t(".every_day")
                - else
                  = schedule.days.map {|d| t(".day_list.#{d}")}.join(", ")

              %td.center
                - if !schedule.enabled?
                  = t(".disabled")
                - else
                  = current_user.formatted_time(schedule.next_run_at)

              %td.center= link_to(t(".history"), history_usercp_schedule_path(schedule._id), :class => "btn btn-inverse btn-mini history")
              %td.center= link_to(t(".edit"), edit_usercp_schedule_path(schedule._id), :class => "btn btn-success btn-mini")
              %td.center= link_to(t(".delete"), usercp_schedule_path(schedule._id), :class => "btn btn-danger btn-mini delete")


#schedule-history.modal.hidden
  .modal-header
    %h3
      = t(".last_schedules", :count => CONFIG[:limit][:schedule_history])
      .close{"data-dismiss" => "modal"} x
  .modal-body
    = image_tag("loading.gif")
    %strong= t("js.loading")
  .modal-footer
    %a.btn.pull-left.btn{:href => "#", "data-dismiss" => "modal"}= t("js.close")

app/views/usercp/schedules/manage.html.haml
.row
  .span12
    %h3.header= @schedule.new_record? ? t(".add_a_schedule") : t(".editing_schedule", :name => @schedule.name)

.row
  .span12
    #error-list
    = form_for @schedule, :url => {:action => @schedule.new_record? ? :create : :update}, :html => {:class => "form-horizontal"} do |f|
      .control-group
        = f.label(:enabled, :class => "control-label")
        .controls
          = f.select(:enabled, [[t("yes"), true], [t("no"), false]], {}, {:class => "input-mini"})
          %span.help-inline= t(".enabled_desc")

      .control-group
        = f.label(:name, :class => "control-label")
        .controls
          = f.text_field(:name, :placeholder => "Porch lights", :class => "input-medium")
          %span.help-inline

      .control-group
        = f.label(:trigger_ids, t("mongo_mapper.attributes.schedule.trigger_ids"), :class => "control-label")
        .controls
          - if current_user.triggers.exists?
            = f.select(:trigger_ids, trigger_list, {:class => "input-medium"}, :multiple => true)
          - else
            = f.select(:trigger_ids, [[t(".none_found"), ""]], {:class => "input-medium"}, :disabled => true, :multiple => true)

          %span.help-inline#trigger-desc= t(".triggers_desc", :limit => CONFIG[:limit][:schedule_triggers])
          %span.help-inline#trigger-limit{"data-limit" => CONFIG[:limit][:schedule_triggers]}
            %span.text-error= t(".triggers_limit", :limit => CONFIG[:limit][:schedule_triggers])

      .control-group.push-bottom
        = f.label(:days, t("mongero_mapper.attributes.schedule.days"), :class => "control-label")
        .controls
          #schedule_days
            %label.toggle-all
              %label.checkbox
                %input{:type => :checkbox}= t(".toggle_all")
            - (1..7).each do |day|
              %label.checkbox.day
                %input{:type => :checkbox, :name => "schedule[days]", :value => day, :checked => @schedule.days.include?(day)}
                = Date::DAYNAMES[day == 7 ? 0 : day]
          %span.help-block= t(".days_desc")

      .tabbable.tabs-left
        %ul.nav.nav-tabs
          %li{:class => (@schedule.new_record? || @schedule.mode == Schedule::TIME) ? :active : nil}= link_to(t(".time"), "#time")
          %li{:class => @schedule.mode == Schedule::SUNRISE ? :active : nil}= link_to(t(".sunrise"), "#sunrise")
          %li{:class => @schedule.mode == Schedule::SUNSET ? :active : nil}= link_to(t(".sunset"), "#sunset")

        .tab-content
          .tab-pane#time
            #current-time{"data-time-offset" => current_user.with_time_zone.utc_offset, "data-time-format" => current_user.time_format(true), "data-time-zone" => current_user.with_time_zone.zone}
              %p
                = linkify_text(t(".currently_time"), edit_usercp_setting_path)

            .control-group
              = f.label(:run_hour, t("mongo_mapper.attributes.schedule.run_hour"), :class => "control-label")
              .controls
                - if current_user.time_mode == User::TWELVE
                  = f.text_field(:run_hour, :placeholder => "8:23 AM", :class => "input-mini")
                  %span.help-inline= t(".run_hour_12_desc")
                - else
                  = f.text_field(:run_hour, :placeholder => "20:21", :class => "input-mini")
                  %span.help-inline= t(".run_hour_24_desc")

            -#.control-group
            -#  = label_tag("schedule_time[run_unless]", t("mongo_mapper.attributes.schedule.run_unless"), :class => "control-label")
            -#  .controls
            -#    = select_tag("schedule_time[run_unless]", options_for_select([[t(".always_run"), Schedule::NONE], [t(".sun_is_down"), Schedule::SUNDOWN], [t(".sun_is_up"), Schedule::SUNUP]], :selected => @schedule.run_unless), :class => "input-medium")
            -#    %span.help-inline= t(".run_unless_desc")

          .tab-pane#sunrise
            - unless @has_location
              %p.warning
                %strong.text-error= t(".sunrise_requires_location")

            .fields{:class => @has_location ? nil : :hidden}
              .time{"data-time" => current_user.solar_event_at(:sunrise)}
                %p
                  = linkify_text(t(".sunrise_at"), edit_usercp_setting_path)

              .control-group
                = label_tag("schedule_sunrise[sun_offset]", t(".sunrise_offset"), :class => "control-label")
                .controls
                  = select_tag("schedule_sunrise[sun_offset]", options_for_select(solar_offset_options(:sunrise), :selected => @schedule.sun_offset), :class => "input-large")
                  %span.help-inline= t(".sunrise_offset_desc")

            -#.control-group
            -#  = label_tag("schedule_sunrise[run_unless]", t("mongo_mapper.attributes.schedule.run_unless"), :class => "control-label")
            -#  .controls
            -#    = select_tag("schedule_sunrise[run_unless]", options_for_select([[t(".always_run"), Schedule::NONE], [t(".sun_is_down"), Schedule::SUNDOWN], [t(".sun_is_up"), Schedule::SUNUP]], :selected => @schedule.run_unless), :class => "input-medium")
            -#    %span.help-inline= t(".run_unless_desc")


          .tab-pane#sunset
            - unless @has_location
              %p.warning
                %strong.text-error= t(".sunrise_requires_location")

            .fields{:class => @has_location ? nil : :hidden}
              .time{"data-time" => current_user.solar_event_at(:sunset)}
                %p
                  = linkify_text(t(".sunset_at"), edit_usercp_setting_path)

              .control-group
                = label_tag("schedule_sunset[sun_offset]", t(".sunset_offset"), :class => "control-label")
                .controls
                  = select_tag("schedule_sunset[sun_offset]", options_for_select(solar_offset_options(:sunset), :selected => @schedule.sun_offset), :class => "input-large")
                  %span.help-inline= t(".sunset_offset_desc")

            -#.control-group
            -#  = label_tag("schedule_sunset[run_unless]", t("mongo_mapper.attributes.schedule.run_unless"), :class => "control-label")
            -#  .controls
            -#    = select_tag("schedule_sunset[run_unless]", options_for_select([[t(".always_run"), Schedule::NONE], [t(".sun_is_down"), Schedule::SUNDOWN], [t(".sun_is_up"), Schedule::SUNUP]], :selected => @schedule.run_unless), :class => "input-medium")
            -#    %span.help-inline= t(".run_unless_desc")

      %input.btn.btn-success{:type => :submit, :value => @schedule.new_record? ? t(".create") : t(".update"), "data-loading-text" => @schedule.new_record? ? t(".creating") : t(".updating")}

- if current_user.flags["hlcsched"]
  - current_user.unset("flags.hlcsched")
  .modal#hlc
    .modal-header
      %h3= t(".hlc.vs_remotehue")
    .modal-body
      %p
        %strong= t(".hlc.desc_1")
      %ol
        - (2..4).each do |i|
          %li= t(".hlc.desc_#{i}")

      %p= t(".hlc.desc_5")
      %p
        %strong= linkify_text(t("contact_support_anytime"), [:email, CONFIG[:contact][:email]])
    .modal-footer
      %a.btn.pull-left.btn-success{:href => "#", "data-dismiss" => "modal"}= t("js.dismiss")

- unless @has_location
  - content_for :head do
    %script{:src => "https://maps.googleapis.com/maps/api/js?v=3.10&sensor=false"}


  = form_tag(inline_location_usercp_setting_path, :method => "PUT", :id => "set-location") do
    .modal.hidden{"data-solar-url" => solar_events_usercp_setting_path}
      .modal-header
        %h3= t(".location_required")
      .modal-body
        %p
          %strong= t(".set_your_location")
        #address
          %input.input-xlarge{:type => "text", :value => t(".new_york_city"), :placeholder => t(".new_york_city")}
          %input.btn.btn-medium.btn-primary{:type => :button, :value => t(".search"), "data-loading-text" => t(".searching")}
        #map


        #solar-time{"data-text" => t(".solar_text")}
          = image_tag("loading.gif")
          %span= t(".loading_sunrise_sunset")

      .modal-footer
        %a.btn.pull-left{:href => "#", "data-dismiss" => "modal"}= t("js.dismiss")
        %input.btn.btn-success.pull-right{:type => :submit, :value => t(".save"), "data-loading-text" => t(".saving")}