config/routes.rb
Remotehue::Application.routes.draw do
  resources :sessions, :only => :new

  get "/ping" => "internal#ping"
  get "/internal/state" => "internal#state"

  scope :module => :api, :as => :api, :path => "/api/v1" do
    controller :mailgun, :as => :mailgun, :path => "/mailgun/:secret" do
      post "/" => :trigger
    end

    controller :trigger, :as => :trigger, :path => "/trigger" do
      post "/:user_id/:trigger_id" => :activate, :as => :activate
    end
  end

  controller :sessions, :path => :sessions, :as => :session do
    get "/logout" => :destroy, :as => :logout
    get "/:provider/callback" => :create
    get "/failure" => :failure
  end

  resources :faq, :only => :index
  resource :subscription, :path => "/subscriptions", :only => :show

  resource :fastspring, :path => "/fastspring/:secret" do
    post "/sub/activated" => :sub_activated
    post "/sub/canceled" => :sub_canceled
    post "/sub/changed" => :sub_changed
    post "/sub/failed" => :sub_failed
    post "/sub/refund" => :sub_refund
    post "/order/notification" => :order_notification
  end

  scope :module => :usercp, :as => :usercp, :path => "" do
    controller :help, :path => :help, :as => :help do
      get "/meethue" => :meethue
      get "/ifttt/:trigger_id" => :ifttt, :as => :ifttt
    end

    resources :bridges do
      collection do
        post "/meethue-login" => :meethue_login, :as => :meethue_login
      end

      member do
        put "/resync" => :resync, :as => :resync
        put "/meethue-login" => :meethue_check, :as => :meethue_check
        put "/update-software" => :update_software, :as => :update_software
        get "/confirm-delete" => :confirm_destroy, :as => :confirm_destroy
      end
    end

    resources :triggers do
      member do
        get "/history" => :history, :as => :history
        get "/usage" => :usage, :as => :usage
        post "/regenerate" => :regenerate, :as => :regenerate
      end
    end

    resources :schedules do
      member do
        get "/usage" => :usage, :as => :usage
        get "/history" => :history, :as => :history
      end
    end

    resources :scenes
    resource :setting do
      member do
        put "/inline-location" => :inline_location, :as => :inline_location
        post "/solar" => :solar_events, :as => :solar_events
      end
    end

    resource :billing
  end

  get "/privacy-policy" => "home#privacy_policy", :as => :privacy_policy
  get "/terms-of-service" => "home#terms_conditions", :as => :terms_conditions
  get "/" => "home#show", :as => :root

  unless Rails.env.production?
    match "/404" => "error#routing"
  end
end

app/models/trigger.rb
class Trigger
  include MongoMapper::Document

  key :name, String
  key :secret, String
  key :secondary_delay, Integer, :default => 0

  timestamps!
  safe

  belongs_to :secondary_trigger, :class_name => "Trigger"
  belongs_to :user

  ensure_index [[:user_id, Mongo::ASCENDING]]

  validates_length_of :name, :minimum => 1, :maximum => 20
  validates_numericality_of :secondary_delay, :minimum => 15, :maximum => 600, :allow_nil => true

  before_create :generate_secret

  def generate_secret
    self.secret = SecureRandom.hex(10)
  end

  def regenerate_secret!
    self.generate_secret
    self.save(:validate => false)
  end

  def mail_tag
    "RemoteHue:#{self.user_id}:#{self.secret}"
  end

  def run_with_log(from, args={})
    history = TriggerHistory.new(args.merge(:user_id => self.user_id, :trigger_id => self._id, :secret => self.secret, :from => from, :created_at => Time.now.utc))
    start = Time.now.to_f

    self.run
    history.results = TriggerHistory::OK

  rescue Exception => e
    history.results = TriggerHistory::EXCEPTION

    raise

  ensure
    history.runtime = Time.now.to_f - start
    history.save
  end

  # MM doesn't handle polymorphic callbacks apparently
  before_save do
    if self.respond_to?(:bridges)
      self.bridges.each {|b| b.run_callbacks(:save)}
    end

    if self.respond_to?(:color)
      self.color.run_callbacks(:save)
    end
  end

  before_validation(:if => lambda {|r| r.respond_to?(:bridges)}) do
    errors.add(:bridges, :at_least) if self.bridges.empty?
  end

  before_validation(:if => lambda {|r| r.respond_to?(:color)}) do
    errors.add(:color, :set) unless self.color?
  end
end

app/models/trigger/bridge.rb
class Trigger::Bridge
  include MongoMapper::EmbeddedDocument

  key :light_ids, Array
  key :group_ids, Array
  belongs_to :bridge

  embedded_in :trigger

  before_save do
    self.light_ids.reject! {|id| !BSON::ObjectId.legal?(id)}
    self.light_ids.map! {|id| id.is_a?(BSON::ObjectId) ? id : BSON::ObjectId(id)}

    self.group_ids.reject! {|id| !BSON::ObjectId.legal?(id)}
    self.group_ids.map! {|id| id.is_a?(BSON::ObjectId) ? id : BSON::ObjectId(id)}
  end

  before_validation do
    if !self.light_ids? and !self.group_ids?
      errors.add(:light_ids, :at_least)
    end
  end
end

app/models/trigger/flash.rb
class Trigger::Flash < Trigger::On
  key :duration, Integer, :default => 0

  def remote_command
    {:alert => self.duration == 0 ? "select" : "lselect"}
  end

  before_validation do
    if self.duration > 0 and !self.color.on
      errors.add(:color, :cant_be_off_multi)
    end
  end
end

app/models/trigger/off.rb
class Trigger::Off < Trigger::On
end

app/models/trigger/scene.rb
class Trigger::Scene < Trigger
  belongs_to :scene

  def run
    self.scene.run
  end
end

app/controllers/api/trigger_controller.rb
class Api::TriggerController < Api::BaseController
  def activate
    res, type = activate_trigger(:api, params[:user_id].to_s, params[:trigger_id].to_s)
    if res == 201
      render :nothing => true, :status => :no_content
    else
      render_error(type)
    end
  end
end

app/controllers/usercp/base_controller.rb
class Usercp::BaseController < ApplicationController
  before_filter :require_logged_in

  def respond_with_model(model, status=:ok)
     if model.errors.empty?
       render :json => {:id => model._id}, :status => status
     else
       data = {:errors => {}.merge(model.errors.messages), :attributes => {}, :scope => model.class.collection_name.singularize}
       data[:errors].each_key {|e| data[:attributes][e] = model.class.human_attribute_name(e)}

       # Check for children
       data[:errors].merge!(load_model_errors(model, data[:attributes]))

       render :json => data, :status => :bad_request
     end
  end

  def load_model_errors(model, attrib_scope)
    errors = {}

    model.associations.each do |key, assoc|
      next unless assoc.embeddable? and model.errors[key]
      embedded = model.send(key)
      next unless embedded

      errors[key] = {}

      # Multiple embedded
      if assoc.is_a?(MongoMapper::Plugins::Associations::ManyAssociation)
        embedded.each do |child|
          next if child.errors.empty?

          errors[key][child._id] = {}.merge(child.errors.messages)
          errors[key][child._id].each_value {|v| v.uniq!}
          errors[key][child._id].each_key {|e| attrib_scope[e] = assoc.klass.human_attribute_name(e)}
          errors[key][child._id].merge!(load_model_errors(child, attrib_scope))
        end

      # Single embedded, merge any errors
      else
        errors[key].merge!(embedded.errors.messages)
        errors[key].each_value {|v| v.uniq!}
        errors[key].each_key {|e| attrib_scope[e] = assoc.klass.human_attribute_name(e)}

        errors[key].merge!(load_model_errors(embedded, attrib_scope))
      end

      if errors[key].empty?
        errors.delete(key)
        next
      end
    end

    errors
  end
end

app/controllers/usercp/billing_controller.rb
class Usercp::BillingController < Usercp::BaseController
  def index

  end
end

app/controllers/usercp/bridges_controller.rb
class Usercp::BridgesController < Usercp::BaseController
  def new
    @bridge = Bridge.new
    @bridge.api_key = Digest::SHA1.hexdigest("#{current_user._id}#{CONFIG[:bridge_secret]}#{current_user.created_at}")

    render :manage
  end

  def edit
    @bridge = Bridge.where(:_id => params[:id].to_s, :user_id => current_user._id).first
    return render_404 unless @bridge

    render :manage
  end

  def update
    bridge = Bridge.where(:_id => params[:id].to_s, :user_id => current_user._id).first
    return render_404 unless bridge

    bridge.api_key = params[:api_key].to_s
    bridge.local_ip = params[:ip].to_s
    bridge.save

    respond_with_model(bridge)
  end

  def resync
    bridge = Bridge.where(:_id => params[:id].to_s, :user_id => current_user._id).first
    return render_404 unless bridge

    unless bridge.manually_resynced?
      bridge.load_data
      bridge.save

      bridge.set(:manually_resynced => true)

      flash[:success] = t("usercp.bridges.index.bridge_resynced", :name => bridge.name)
    end

    render :nothing => true, :status => :no_content
  end

  def meethue_check
    bridge = Bridge.where(:_id => params[:id].to_s, :user_id => current_user._id).first
    return render_404 unless bridge

    bridge.load_data
    bridge.save
    flash[:success] = t("usercp.bridges.manage.bridge_saved", :name => bridge.name) if bridge.errors.empty?

    respond_with_model(bridge)
  end

  def meethue_login
    if params[:id]
      bridge = Bridge.where(:_id => params[:id].to_s, :user_id => current_user._id).first
      return render_404 unless bridge
    else
      bridge = Bridge.new
      bridge.user = current_user
      bridge.api_key = params[:api_key].to_s
      bridge.local_ip = params[:ip].to_s
    end

    email, password = params[:email].to_s.strip, params[:password].to_s.strip
    bridge_id = params[:bridge_id].to_s.strip
    if email.blank? or password.blank? or bridge_id !~ /\A[a-z0-9]+\z/
      return render_404
    end

    # Get our session
    res = Stats.network("meethue.gettoken") do
      Excon.get("https://www.meethue.com/en-US/api/gettoken?devicename=Remote+Hue&appid=hueapp&deviceid=#{bridge.api_key}", :headers => {"User-Agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.65 Safari/537.36"})
    end
    cookie = res.headers["Set-Cookie"]
    unless cookie.match(/PLAY_SESSION="(.+)"/)
      return render :json => {:error => "session"}, :status => :bad_request
    end

    # Login as the user
    last_url = "https://www.meethue.com/en-US/api/gettoken?devicename=Remote+Hue&appid=hueapp&deviceid=#{bridge.api_key}"
    res = Stats.network("meethue.getaccesstoken") do
      Excon.post("https://www.meethue.com/en-US/api/getaccesstokengivepermission", :headers => {"Content-Type" => "application/x-www-form-urlencoded; charset=UTF-8", "Cookie" => "PLAY_SESSION=\"#{$1}\"", "User-Agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.65 Safari/537.36", :"Referer" => last_url}, :body => {:email => email, :password => password}.to_query)
    end
    if res.status == 302
      if res.headers["Set-Cookie"] =~ /PLAY_FLASH="(.+)"/
        return render :json => {:error => $1 =~ /authentication/i ? "auth" : "unknown0"}, :status => :bad_request
      else
        return render :json => {:error => "unknown1"}, :status => :bad_request
      end

    elsif res.status != 200 or res.body !~ /requesting access/i
      return render :json => {:error => "unknown2"}, :status => :bad_request
    end

    # Get any updated session info
    cookie = res.headers["Set-Cookie"]
    unless cookie.match(/PLAY_SESSION="(.+)"/)
      return render :json => {:error => "session"}, :status => :bad_request
    end

    # Now do the last bit of confirmation that we confirm
    last_url = "https://www.meethue.com/en-US/api/getaccesstokengivepermission"
    res = Stats.network("meethue.getaccesstokenpost") do
      Excon.get("https://www.meethue.com/en-US/api/getaccesstokenpost", :headers => {:"Content-Type" => "application/x-www-form-urlencoded; charset=UTF-8", "Cookie" => "PLAY_SESSION=\"#{$1}\"", :"Referer" => last_url, :"User-Agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.65 Safari/537.36"})
    end
    if res.status == 200
      if res.body =~ %r{phhueapp://sdk/login/([a-zA-Z0-9/=\+]+)}
        current_user.set(:pending_token => $1)

        bridge.bridge_id = bridge_id
        bridge.meethue_token = $1
        bridge.load_data
        bridge.next_update_at = Time.now.utc + rand(4).hours
        bridge.save

        current_user.unset(:pending_token)

        flash[:success] = t("usercp.bridges.manage.#{!params[:id] ? "bridge_created" : "bridge_saved"}", :name => bridge.name) if bridge.errors.empty?
        respond_with_model(bridge, :created)
      else
        return render :json => {:error => "unknown3"}, :status => :bad_request
      end
    else
      return render :json => {:error => "unknown4"}, :status => :bad_request
    end
  end

  def index
    @bridges = current_user.bridges.sort_by {|b| b.name}

  end

  def update_software

  end

  def confirm_destroy

  end

  private
end

app/controllers/usercp/help_controller.rb
class Usercp::HelpController < Usercp::BaseController
  def meethue

  end

  def ifttt
    @trigger = current_user.triggers.where(:_id => params[:trigger_id].to_s).first
    return render_404 unless @trigger
  end
end

app/controllers/usercp/scenes_controller.rb
class Usercp::ScenesController < Usercp::BaseController
  def index

  end
end

app/controllers/usercp/schedules_controller.rb
class Usercp::SchedulesController < Usercp::BaseController
  def index
    @schedules = current_user.schedules.sort_by {|t| t.name}
  end

  def new
    @schedule = Schedule.new
    @has_location = current_user.latitude? && current_user.longitude?

    render :manage
  end

  def create
    manage_schedule(Schedule.new(:user => current_user))
  end

  def history
    @schedule = current_user.schedules.where(:_id => params[:id].to_s).only(:name).first
    return render_404 unless @schedule

    @history = current_user.schedule_history.where(:schedule_id => @schedule._id).sort(:_id.desc).map {|h| h}
    render :layout => false
  end

  def edit
    @schedule = current_user.schedules.where(:_id => params[:id].to_s).first
    return render_404 unless @schedule
    @has_location = current_user.latitude? && current_user.longitude?

    render :manage
  end

  def update
    schedule = current_user.schedules.where(:_id => params[:id].to_s).first
    return render_404 unless schedule
    manage_schedule(schedule)
  end

  def destroy
    schedule = current_user.schedules.where(:_id => params[:id].to_s).first
    if schedule
      schedule.destroy
    end

    render :nothing => true, :status => :no_content
  end

  private
  def manage_schedule(schedule)
    schedule.name = params[:name].to_s
    schedule.enabled = params[:enabled] == "true"
    schedule.mode = case params[:type]
      when "sunset" then Schedule::SUNSET
      when "sunrise" then Schedule::SUNRISE
      else Schedule::TIME
    end
    schedule.days = []

    if params[:days].is_a?(Array)
      params[:days].each do |day|
        day = day.to_i

        schedule.days.push(day) if day >= 1 and day <= 7
      end
    end

    if params[:trigger_ids].is_a?(Array)
      ids = params[:trigger_ids].select {|id| BSON::ObjectId.legal?(id)}
      schedule.trigger_ids = current_user.triggers.where(:_id.in => ids).only(:_id).map do |trigger|
        trigger._id
      end

    else
      schedule.trigger_ids = []
    end

    schedule.run_unless = params[:run_unless].to_i

    if schedule.mode == Schedule::TIME
      schedule.run_hour = params[:run_hour].to_s.gsub(/[^\sapm0-9:]+/i, "")
    elsif schedule.mode == Schedule::SUNRISE
      schedule.sun_offset = params[:sun_offset].to_i
    elsif schedule.mode == Schedule::SUNSET
      schedule.sun_offset = params[:sun_offset].to_i
    end

    if schedule.valid?
      schedule.next_run_at = schedule.calc_next_run
    end
    schedule.save

    if schedule.errors.empty? and schedule.next_run_at <= 10.minutes.from_now.utc
      SchedulerDispatch.perform_async
    end

    if schedule.errors.empty?
      flash[:success] = t("usercp.schedules.manage.schedule_#{params[:action] == "create" ? "created" : "updated"}", :name => schedule.name)
    end

    respond_with_model(schedule)
  end
end

app/controllers/usercp/settings_controller.rb
class Usercp::SettingsController < Usercp::BaseController
  def index

  end

  def edit

  end

  def update
    user = User.where(:_id => current_user._id).first
    user.full_name = params[:full_name].to_s
    user.email = params[:email].to_s
    user.timezone = params[:timezone].to_s
    user.time_mode = params[:time_mode].to_i
    user.latitude = params[:latitude].to_f
    user.longitude = params[:longitude].to_f
    user.email_market = params[:email_market] != "false"

    if user.valid?
      flash[:success] = t("usercp.settings.edit.settings_updated")
    end

    user.save
    respond_with_model(user)
  end


  def inline_location
    current_user.latitude = params[:latitude].to_f
    current_user.longitude = params[:longitude].to_f
    current_user.save

    solar_events
  end

  def solar_events
    require Rails.root.join("lib", "solar_event")
    se = SolarEvent.new(Date.today, params[:latitude].to_f.to_d, params[:longitude].to_f.to_d)
    sunrise = se.send("compute_official_sunrise", current_user.timezone)
    sunset = se.send("compute_official_sunset", current_user.timezone)

    render :json => {:sunrise => current_user.formatted_hour(sunrise, false), :sunset => current_user.formatted_hour(sunset, false), :timezone => current_user.with_time_zone.zone}
  end
end

app/views/usercp/triggers/_color.html.haml
.control-group
  = label_tag(:trigger_color, t("usercp.triggers.manage.color_bri"), :class => "control-label")
  .controls
    .colorpicker{"data-color" => color.to_json(:except => [:id, :on, :_type, :transitiontime])}
      .colors.draggable
        .pointer
          .inner-border
        .ct
        .hs

      .bri-container
        .bri.draggable
          .pointer
            .inner-border

app/views/usercp/triggers/_lights.html.haml
- bridges = current_user.bridges {|b| b[:name]}
.control-group
  = label_tag(:trigger_lights, t("usercp.triggers.manage.lights"), :class => "control-label")
  .controls
    %select.select-xlarge{:id => "trigger_lights", :name => "trigger[lights]", :multiple => true}
      - bridges.each do |bridge|
        %optgroup{:label => bridge.name}
          - bridge.lights.each do |light|
            %option{:value => "#{bridge._id}_#{light._id}", "data-color" => light.color?, :selected => active_lights[bridge._id] && active_lights[bridge._id][light._id]}= light.name

.control-group
  = label_tag(:trigger_groups, t("usercp.triggers.manage.groups"), :class => "control-label")
  .controls
    %select.select-xlarge{:id => "trigger_groups", :name => "trigger[groups]", :multiple => true}
      - bridges.each do |bridge|
        %optgroup{:label => bridge.name}
          - bridge.groups.each do |group|
            %option{:value => "#{bridge._id}_#{group._id}", :selected => active_groups[bridge._id] && active_groups[bridge._id][group._id]}= group.name

app/views/usercp/triggers/history.html.haml
%table.table.table-hover.table-striped.table-bordered
  %thead
    %tr
      %th= t(".source")
      %th.center= t(".results")
      %th= t(".created_at")

  %tbody
    - if @history.empty?
      %tr
        %td{:colspan => 3}= t(".not_triggered_yet", :name => @trigger.name)

    - else
      - @history.each do |row|
        %tr
          %td= t(".from_types.#{row.from}")
          %td.center
            = t(".result_types.#{row.results}")
            %a.tt{"title" => t(".result_types_desc.#{row.results}"), :href => "#"} [?]
          %td= current_user.formatted_time(row.created_at)

:javascript
  $("#trigger-history .tt").tooltip();

app/views/usercp/triggers/index.html.haml
.row
  .span12
    %h3.header= t(".triggers_index")

- if @triggers.empty?
  .row
    .span12
      .alert.alert-block
        .close{"data-dismiss" => :alert} x
        %h4= t(".no_triggers_found")
        = linkify_text(t(".add_a_trigger"), new_usercp_trigger_path)

- else
  .row
    .span12
      %table.table.table-hover.table-striped.table-bordered
        %thead
          %tr
            %th= t(".name")
            %th.center= t(".type")
            %th.center= t(".ifttt_setup")
            %th.center= t(".api_setup")
            %th.center= t(".history")
            %th.center= t(".edit")
            %th.center= t(".delete")

        %tbody
          - @triggers.each do |trigger|
            %tr
              %td= trigger.name
              %td.center= t("trigger_types.#{trigger._type}")
              %td.center= link_to(t(".ifttt_setup"), usercp_help_ifttt_path(trigger._id), :class => "btn btn-primary btn-mini")
              %td.center= link_to(t(".api_setup"), usage_usercp_trigger_path(trigger._id), :class => "btn btn-mini setup", "data-regenerate" => regenerate_usercp_trigger_path(trigger._id))
              %td.center= link_to(t(".history"), history_usercp_trigger_path(trigger._id), :class => "btn btn-inverse btn-mini history")
              %td.center= link_to(t(".edit"), edit_usercp_trigger_path(trigger._id), :class => "btn btn-success btn-mini")
              %td.center= link_to(t(".delete"), usercp_trigger_path(trigger._id), :class => "btn btn-danger btn-mini delete")

#trigger-setup.modal.hidden
  .modal-header
    %h3
      = t(".api_usage")
      .close{"data-dismiss" => "modal"} x
  .modal-body
    = image_tag("loading.gif")
    %strong= t("js.loading")
  .modal-footer
    %a.btn.pull-left.btn{:href => "#", "data-dismiss" => "modal"}= t("js.close")
    %a.btn.pull-right.btn-danger{:href => "#", "data-loading-text" => t(".regenerating")}= t(".regenerate")

#trigger-history.modal.hidden
  .modal-header
    %h3
      = t(".last_triggers", :count => CONFIG[:limit][:trigger_history])
      .close{"data-dismiss" => "modal"} x
  .modal-body
    = image_tag("loading.gif")
    %strong= t("js.loading")
  .modal-footer
    %a.btn.pull-left.btn{:href => "#", "data-dismiss" => "modal"}= t("js.close")

app/views/usercp/triggers/manage.html.haml
.row
  .span12
    %h3.header= @trigger.new_record? ? t(".add_a_trigger") : t(".editing_trigger", :name => @trigger.name)

.row
  .span12
    #error-list
    = form_for @trigger, :url => {:action => @trigger.new_record? ? :create : :update}, :html => {:class => "form-horizontal"} do |f|
      .control-group
        = label_tag("trigger[name]", t(".name"), :class => "control-label")
        .controls
          = text_field_tag("trigger[name]", @trigger.name, :placeholder => "Flash office lights", :class => "input-medium")
          %span.help-inline

      .control-group
        = label_tag("trigger[transitiontime]", t(".transitiontime"), :class => "control-label")
        .controls
          = select_tag("trigger[transitiontime]", options_for_select(transitiontime_list, :selected => @trigger.respond_to?(:color) && @trigger.color && @trigger.color.transitiontime || 0), :class => "input-medium")
          %span.help-inline= t(".transitiontime_desc")

      .tabbable.tabs-left
        %ul.nav.nav-tabs
          %li{:class => (@trigger.new_record? || @trigger.instance_of?(Trigger::Flash)) ? :active : nil}= link_to(t(".flash_lights"), "#flash")
          -#%li{:class => @trigger.instance_of?(Trigger::Scene) ? :active : nil}= link_to(t(".run_scene"), "#scene")
          %li{:class => @trigger.instance_of?(Trigger::Off) ? :active : nil}= link_to(t(".lights_off"), "#off")
          %li{:class => @trigger.instance_of?(Trigger::On) ? :active : nil}= link_to(t(".lights_on"), "#on")

        .tab-content
          .tab-pane#flash
            .control-group
              = label_tag("trigger[duration]", t(".duration"), :class => "control-label")
              .controls
                = select_tag("trigger[duration]", options_for_select([[t(".once"), 0], [t(".flash_seconds", :seconds => 30), 30]], :selected => @trigger.respond_to?(:duration) ? @trigger.duration : 0), :class => "input-medium")
                %span.help-inline

            = render :partial => "lights", :locals => {:active_lights => @active_lights, :active_groups => @active_groups}
            = render :partial => "color", :locals => {:color => @trigger.respond_to?(:color) && @trigger.color, :fallback_color => @trigger.respond_to?(:fallback_color) && @trigger.fallback_color}

          .tab-pane#scene

          .tab-pane#off
            = render :partial => "lights", :locals => {:active_lights => @active_lights, :active_groups => @active_groups}

          .tab-pane#on
            = render :partial => "lights", :locals => {:active_lights => @active_lights, :active_groups => @active_groups}
            = render :partial => "color", :locals => {:color => @trigger.respond_to?(:color) && @trigger.color, :fallback_color => @trigger.respond_to?(:fallback_color) && @trigger.fallback_color}

      - secondary_triggers = Trigger.where(:user_id => current_user._id, :_id.ne => @trigger._id).sort(:name).only(:name).map {|t| [t.name, t._id]}
      - if secondary_triggers
        .control-group#secondary_disclaimer
          %p= t(".only_run_on_api_mailgun")

      .control-group
        = label_tag("trigger[secondary_trigger_id]", t(".secondary_trigger"), :class => "control-label")
        .controls
          = select_tag("trigger[secondary_trigger_id]", options_for_select(secondary_triggers.empty? ? [[t(".no_triggers_found"), ""]] : [[t(".dont_run_secondary"), ""]].concat(secondary_triggers), :selected => @trigger.secondary_trigger_id), :disabled => secondary_triggers.empty?, :class => "input-medium")
          %span.help-inline{"data-this-one" => t(".this_one")}= t(".secondary_trigger_desc")

      .control-group
        = label_tag("trigger[secondary_delay]", t(".secondary_delay"), :class => "control-label")
        .controls
          = select_tag("trigger[secondary_delay]", options_for_select([[t(".after_seconds", :seconds => 15), 15], [t(".after_seconds", :seconds => 30), 30], [t(".after_seconds", :seconds => 45), 45], [t(".after_seconds", :seconds => 60), 60],[t(".after_minutes", :minutes => 5), 300], [t(".after_minutes", :minutes => 10), 600]], :selected => @trigger.secondary_delay), :disabled => secondary_triggers.empty?, :class => "input-medium")
          %span.help-inline= t(".secondary_delay_desc")

      %input.btn.btn-success{:type => :submit, :value => @trigger.new_record? ? t(".create") : t(".update"), "data-loading-text" => @trigger.new_record? ? t(".creating") : t(".updating")}

app/views/usercp/triggers/usage.html.haml
%p
  %strong= linkify_text(t(".ifttt_setup_info"), usercp_help_ifttt_path(@trigger._id))

%p.text-error= t(".tags_secret")

%p
  %strong= t(".api_info")

%input.input-full{:type => :text, :value => api_trigger_activate_url(current_user._id, @trigger.secret)}

%p
  = t(".api_info_it")