config/routes.rb
Remotehue::Application.routes.draw do
  resources :sessions, :only => :new

  get "/ping" => "internal#ping"
  get "/internal/state" => "internal#state"

  scope :module => :api, :as => :api, :path => "/api/v1" do
    controller :mailgun, :as => :mailgun, :path => "/mailgun/:secret" do
      post "/" => :trigger
    end

    controller :trigger, :as => :trigger, :path => "/trigger" do
      post "/:user_id/:trigger_id" => :activate, :as => :activate
    end
  end

  controller :sessions, :path => :sessions, :as => :session do
    get "/logout" => :destroy, :as => :logout
    get "/:provider/callback" => :create
    get "/failure" => :failure
  end

  resources :faq, :only => :index
  resource :subscription, :path => "/subscriptions", :only => :show

  resource :fastspring, :path => "/fastspring/:secret" do
    post "/sub/activated" => :sub_activated
    post "/sub/canceled" => :sub_canceled
    post "/sub/changed" => :sub_changed
    post "/sub/failed" => :sub_failed
    post "/sub/refund" => :sub_refund
    post "/order/notification" => :order_notification
  end

  scope :module => :usercp, :as => :usercp, :path => "" do
    controller :help, :path => :help, :as => :help do
      get "/meethue" => :meethue
      get "/ifttt/:trigger_id" => :ifttt, :as => :ifttt
    end

    resources :bridges do
      collection do
        post "/meethue-login" => :meethue_login, :as => :meethue_login
      end

      member do
        put "/resync" => :resync, :as => :resync
        put "/meethue-login" => :meethue_check, :as => :meethue_check
        put "/update-software" => :update_software, :as => :update_software
        get "/confirm-delete" => :confirm_destroy, :as => :confirm_destroy
      end
    end

    resources :triggers do
      member do
        get "/history" => :history, :as => :history
        get "/usage" => :usage, :as => :usage
        post "/regenerate" => :regenerate, :as => :regenerate
      end
    end

    resources :schedules do
      member do
        get "/usage" => :usage, :as => :usage
        get "/history" => :history, :as => :history
      end
    end

    resources :scenes
    resource :setting do
      member do
        put "/inline-location" => :inline_location, :as => :inline_location
        post "/solar" => :solar_events, :as => :solar_events
      end
    end

    resource :billing
  end

  get "/privacy-policy" => "home#privacy_policy", :as => :privacy_policy
  get "/terms-of-service" => "home#terms_conditions", :as => :terms_conditions
  get "/" => "home#show", :as => :root

  unless Rails.env.production?
    match "/404" => "error#routing"
  end
end

app/models/trigger/bridge.rb
class Trigger::Bridge
  include MongoMapper::EmbeddedDocument

  key :light_ids, Array
  key :group_ids, Array
  belongs_to :bridge

  embedded_in :trigger

  before_save do
    self.light_ids.reject! {|id| !BSON::ObjectId.legal?(id)}
    self.light_ids.map! {|id| id.is_a?(BSON::ObjectId) ? id : BSON::ObjectId(id)}

    self.group_ids.reject! {|id| !BSON::ObjectId.legal?(id)}
    self.group_ids.map! {|id| id.is_a?(BSON::ObjectId) ? id : BSON::ObjectId(id)}
  end

  before_validation do
    if !self.light_ids? and !self.group_ids?
      errors.add(:light_ids, :at_least)
    end
  end
end

app/controllers/usercp/base_controller.rb
class Usercp::BaseController < ApplicationController
  before_filter :require_logged_in

  def respond_with_model(model, status=:ok)
     if model.errors.empty?
       render :json => {:id => model._id}, :status => status
     else
       data = {:errors => {}.merge(model.errors.messages), :attributes => {}, :scope => model.class.collection_name.singularize}
       data[:errors].each_key {|e| data[:attributes][e] = model.class.human_attribute_name(e)}

       # Check for children
       data[:errors].merge!(load_model_errors(model, data[:attributes]))

       render :json => data, :status => :bad_request
     end
  end

  def load_model_errors(model, attrib_scope)
    errors = {}

    model.associations.each do |key, assoc|
      next unless assoc.embeddable? and model.errors[key]
      embedded = model.send(key)
      next unless embedded

      errors[key] = {}

      # Multiple embedded
      if assoc.is_a?(MongoMapper::Plugins::Associations::ManyAssociation)
        embedded.each do |child|
          next if child.errors.empty?

          errors[key][child._id] = {}.merge(child.errors.messages)
          errors[key][child._id].each_value {|v| v.uniq!}
          errors[key][child._id].each_key {|e| attrib_scope[e] = assoc.klass.human_attribute_name(e)}
          errors[key][child._id].merge!(load_model_errors(child, attrib_scope))
        end

      # Single embedded, merge any errors
      else
        errors[key].merge!(embedded.errors.messages)
        errors[key].each_value {|v| v.uniq!}
        errors[key].each_key {|e| attrib_scope[e] = assoc.klass.human_attribute_name(e)}

        errors[key].merge!(load_model_errors(embedded, attrib_scope))
      end

      if errors[key].empty?
        errors.delete(key)
        next
      end
    end

    errors
  end
end

app/controllers/usercp/billing_controller.rb
class Usercp::BillingController < Usercp::BaseController
  def index

  end
end

app/controllers/usercp/bridges_controller.rb
class Usercp::BridgesController < Usercp::BaseController
  def new
    @bridge = Bridge.new
    @bridge.api_key = Digest::SHA1.hexdigest("#{current_user._id}#{CONFIG[:bridge_secret]}#{current_user.created_at}")

    render :manage
  end

  def edit
    @bridge = Bridge.where(:_id => params[:id].to_s, :user_id => current_user._id).first
    return render_404 unless @bridge

    render :manage
  end

  def update
    bridge = Bridge.where(:_id => params[:id].to_s, :user_id => current_user._id).first
    return render_404 unless bridge

    bridge.api_key = params[:api_key].to_s
    bridge.local_ip = params[:ip].to_s
    bridge.save

    respond_with_model(bridge)
  end

  def resync
    bridge = Bridge.where(:_id => params[:id].to_s, :user_id => current_user._id).first
    return render_404 unless bridge

    unless bridge.manually_resynced?
      bridge.load_data
      bridge.save

      bridge.set(:manually_resynced => true)

      flash[:success] = t("usercp.bridges.index.bridge_resynced", :name => bridge.name)
    end

    render :nothing => true, :status => :no_content
  end

  def meethue_check
    bridge = Bridge.where(:_id => params[:id].to_s, :user_id => current_user._id).first
    return render_404 unless bridge

    bridge.load_data
    bridge.save
    flash[:success] = t("usercp.bridges.manage.bridge_saved", :name => bridge.name) if bridge.errors.empty?

    respond_with_model(bridge)
  end

  def meethue_login
    if params[:id]
      bridge = Bridge.where(:_id => params[:id].to_s, :user_id => current_user._id).first
      return render_404 unless bridge
    else
      bridge = Bridge.new
      bridge.user = current_user
      bridge.api_key = params[:api_key].to_s
      bridge.local_ip = params[:ip].to_s
    end

    email, password = params[:email].to_s.strip, params[:password].to_s.strip
    bridge_id = params[:bridge_id].to_s.strip
    if email.blank? or password.blank? or bridge_id !~ /\A[a-z0-9]+\z/
      return render_404
    end

    # Get our session
    res = Stats.network("meethue.gettoken") do
      Excon.get("https://www.meethue.com/en-US/api/gettoken?devicename=Remote+Hue&appid=hueapp&deviceid=#{bridge.api_key}", :headers => {"User-Agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.65 Safari/537.36"})
    end
    cookie = res.headers["Set-Cookie"]
    unless cookie.match(/PLAY_SESSION="(.+)"/)
      return render :json => {:error => "session"}, :status => :bad_request
    end

    # Login as the user
    last_url = "https://www.meethue.com/en-US/api/gettoken?devicename=Remote+Hue&appid=hueapp&deviceid=#{bridge.api_key}"
    res = Stats.network("meethue.getaccesstoken") do
      Excon.post("https://www.meethue.com/en-US/api/getaccesstokengivepermission", :headers => {"Content-Type" => "application/x-www-form-urlencoded; charset=UTF-8", "Cookie" => "PLAY_SESSION=\"#{$1}\"", "User-Agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.65 Safari/537.36", :"Referer" => last_url}, :body => {:email => email, :password => password}.to_query)
    end
    if res.status == 302
      if res.headers["Set-Cookie"] =~ /PLAY_FLASH="(.+)"/
        return render :json => {:error => $1 =~ /authentication/i ? "auth" : "unknown0"}, :status => :bad_request
      else
        return render :json => {:error => "unknown1"}, :status => :bad_request
      end

    elsif res.status != 200 or res.body !~ /requesting access/i
      return render :json => {:error => "unknown2"}, :status => :bad_request
    end

    # Get any updated session info
    cookie = res.headers["Set-Cookie"]
    unless cookie.match(/PLAY_SESSION="(.+)"/)
      return render :json => {:error => "session"}, :status => :bad_request
    end

    # Now do the last bit of confirmation that we confirm
    last_url = "https://www.meethue.com/en-US/api/getaccesstokengivepermission"
    res = Stats.network("meethue.getaccesstokenpost") do
      Excon.get("https://www.meethue.com/en-US/api/getaccesstokenpost", :headers => {:"Content-Type" => "application/x-www-form-urlencoded; charset=UTF-8", "Cookie" => "PLAY_SESSION=\"#{$1}\"", :"Referer" => last_url, :"User-Agent" => "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.65 Safari/537.36"})
    end
    if res.status == 200
      if res.body =~ %r{phhueapp://sdk/login/([a-zA-Z0-9/=\+]+)}
        current_user.set(:pending_token => $1)

        bridge.bridge_id = bridge_id
        bridge.meethue_token = $1
        bridge.load_data
        bridge.next_update_at = Time.now.utc + rand(4).hours
        bridge.save

        current_user.unset(:pending_token)

        flash[:success] = t("usercp.bridges.manage.#{!params[:id] ? "bridge_created" : "bridge_saved"}", :name => bridge.name) if bridge.errors.empty?
        respond_with_model(bridge, :created)
      else
        return render :json => {:error => "unknown3"}, :status => :bad_request
      end
    else
      return render :json => {:error => "unknown4"}, :status => :bad_request
    end
  end

  def index
    @bridges = current_user.bridges.sort_by {|b| b.name}

  end

  def update_software

  end

  def confirm_destroy

  end

  private
end

app/controllers/usercp/help_controller.rb
class Usercp::HelpController < Usercp::BaseController
  def meethue

  end

  def ifttt
    @trigger = current_user.triggers.where(:_id => params[:trigger_id].to_s).first
    return render_404 unless @trigger
  end
end

app/controllers/usercp/scenes_controller.rb
class Usercp::ScenesController < Usercp::BaseController
  def index

  end
end

app/controllers/usercp/schedules_controller.rb
class Usercp::SchedulesController < Usercp::BaseController
  def index
    @schedules = current_user.schedules.sort_by {|t| t.name}
  end

  def new
    @schedule = Schedule.new
    @has_location = current_user.latitude? && current_user.longitude?

    render :manage
  end

  def create
    manage_schedule(Schedule.new(:user => current_user))
  end

  def history
    @schedule = current_user.schedules.where(:_id => params[:id].to_s).only(:name).first
    return render_404 unless @schedule

    @history = current_user.schedule_history.where(:schedule_id => @schedule._id).sort(:_id.desc).map {|h| h}
    render :layout => false
  end

  def edit
    @schedule = current_user.schedules.where(:_id => params[:id].to_s).first
    return render_404 unless @schedule
    @has_location = current_user.latitude? && current_user.longitude?

    render :manage
  end

  def update
    schedule = current_user.schedules.where(:_id => params[:id].to_s).first
    return render_404 unless schedule
    manage_schedule(schedule)
  end

  def destroy
    schedule = current_user.schedules.where(:_id => params[:id].to_s).first
    if schedule
      schedule.destroy
    end

    render :nothing => true, :status => :no_content
  end

  private
  def manage_schedule(schedule)
    schedule.name = params[:name].to_s
    schedule.enabled = params[:enabled] == "true"
    schedule.mode = case params[:type]
      when "sunset" then Schedule::SUNSET
      when "sunrise" then Schedule::SUNRISE
      else Schedule::TIME
    end
    schedule.days = []

    if params[:days].is_a?(Array)
      params[:days].each do |day|
        day = day.to_i

        schedule.days.push(day) if day >= 1 and day <= 7
      end
    end

    if params[:trigger_ids].is_a?(Array)
      ids = params[:trigger_ids].select {|id| BSON::ObjectId.legal?(id)}
      schedule.trigger_ids = current_user.triggers.where(:_id.in => ids).only(:_id).map do |trigger|
        trigger._id
      end

    else
      schedule.trigger_ids = []
    end

    schedule.run_unless = params[:run_unless].to_i

    if schedule.mode == Schedule::TIME
      schedule.run_hour = params[:run_hour].to_s.gsub(/[^\sapm0-9:]+/i, "")
    elsif schedule.mode == Schedule::SUNRISE
      schedule.sun_offset = params[:sun_offset].to_i
    elsif schedule.mode == Schedule::SUNSET
      schedule.sun_offset = params[:sun_offset].to_i
    end

    if schedule.valid?
      schedule.next_run_at = schedule.calc_next_run
    end
    schedule.save

    if schedule.errors.empty? and schedule.next_run_at <= 10.minutes.from_now.utc
      SchedulerDispatch.perform_async
    end

    if schedule.errors.empty?
      flash[:success] = t("usercp.schedules.manage.schedule_#{params[:action] == "create" ? "created" : "updated"}", :name => schedule.name)
    end

    respond_with_model(schedule)
  end
end

app/controllers/usercp/settings_controller.rb
class Usercp::SettingsController < Usercp::BaseController
  def index

  end

  def edit

  end

  def update
    user = User.where(:_id => current_user._id).first
    user.full_name = params[:full_name].to_s
    user.email = params[:email].to_s
    user.timezone = params[:timezone].to_s
    user.time_mode = params[:time_mode].to_i
    user.latitude = params[:latitude].to_f
    user.longitude = params[:longitude].to_f
    user.email_market = params[:email_market] != "false"

    if user.valid?
      flash[:success] = t("usercp.settings.edit.settings_updated")
    end

    user.save
    respond_with_model(user)
  end


  def inline_location
    current_user.latitude = params[:latitude].to_f
    current_user.longitude = params[:longitude].to_f
    current_user.save

    solar_events
  end

  def solar_events
    require Rails.root.join("lib", "solar_event")
    se = SolarEvent.new(Date.today, params[:latitude].to_f.to_d, params[:longitude].to_f.to_d)
    sunrise = se.send("compute_official_sunrise", current_user.timezone)
    sunset = se.send("compute_official_sunset", current_user.timezone)

    render :json => {:sunrise => current_user.formatted_hour(sunrise, false), :sunset => current_user.formatted_hour(sunset, false), :timezone => current_user.with_time_zone.zone}
  end
end

app/views/usercp/bridges/index.html.haml
.row
  .span12
    %h3.header= t(".bridge_index")

- if @bridges.empty?
  .row
    .span12
      .alert.alert-block
        .close{"data-dismiss" => :alert} x
        %h4= t(".no_bridges_found")
        = linkify_text(t(".add_a_bridge"), new_usercp_bridge_path)

- else
  .row
    .span12
      %table.table.table-hover.table-striped.table-bordered
        %thead
          %tr
            %th= t(".name")
            %th= t(".local_ip")
            %th= t(".mac")
            %th.center= t(".bridge_software")
            %th.center= t(".lights")
            %th.center= t(".resync")
            %th.center= t(".edit")
            -#%th= t(".delete")

        %tbody
          - @bridges.each do |bridge|
            %tr
              %td= bridge.name
              %td= bridge.local_ip_text
              %td= bridge.mac_text
              %td.center
                - if bridge.update_state == Bridge::UPDATE_AVAILABLE
                  -#%a.btn.btn-mini.btn-success{:href => update_software_usercp_bridge_path(bridge._id), "data-tooltip" => t(".update_available")}
                  -#  Update
                  %span.text-success= t(".update_short")
                - elsif bridge.update_state == Bridge::UPDATING
                  %span.text-success= t(".updating")
                - else
                  v#{bridge.swversion}
              %td.center= t("lights", :count => bridge.lights.length)
              %td.center
                - if bridge.manually_resynced?
                  %span.text-error.tt{:title => t(".resync_used_desc", :time => current_user.formatted_time(bridge.next_update_at, false))}
                    = t(".resync_used")
                    [?]
                - else
                  = link_to(t(".resync"), resync_usercp_bridge_path(bridge._id), :class => "btn btn-primary btn-mini tt resync", :title => t(".manual_resync"), "data-loading-text" => t(".resyncing"))

              %td.center= link_to(t(".edit"), edit_usercp_bridge_path(bridge._id), :class => "btn btn-success btn-mini")
              -#%td.center= link_to(t(".delete"), confirm_destroy_usercp_bridge_path(bridge._id), :class => "btn btn-danger btn-small")

app/views/usercp/bridges/manage.html.haml
.row
  .span12
    %h3.header= @bridge.new_record? ? t(".add_a_bridge") : t(".editing_bridge", :name => @bridge.name)

.row
  .span12
    #error-list


  .span12#step1
    %h4= t(".step_1")
    = form_for @bridge, :url => {:action => @bridge.new_record? ? :create : :update}, :html => {:class => "form-horizontal"} do |f|
      %p= t(".bridge_local_net")

      .control-group
        = f.label(:local_ip, :class => "control-label")
        .controls
          = f.text_field(:local_ip, :placeholder => "192.168.1.100", :value => @bridge.local_ip_text, :class => "input-medium")
          %span.help-inline

      - if @bridge.new_record?
        = f.hidden_field(:api_key)
      - else
        .control-group
          = f.label(:api_key, :class => "control-label")
          .controls
            = f.text_field(:api_key, :disabled => true, :class => "input-xlarge")

      .control-group
        = f.label(:status, :class => "control-label")
        .controls
          - if @bridge.new_record? or @bridge.status == Bridge::UNAUTHORIZED
            %p.text-error.lead#bridge-status= t(".authorization_required")
          - elsif @bridge.status == Bridge::ACTIVE
            %p.text-success.lead#bridge-status= t(".authorized")
          - elsif @bridge.status == Bridge::OFFLINE
            %p.text-error.lead#bridge-status= t(".offline")
          - else
            %p.text-error.lead#bridge-status= t(".unknown")

      %input.btn.btn-success{:type => :submit, :value => t(".next"), "data-loading-text" => t(".checking"), "data-saving-text" => t(".saving")}

  .span12#step2.hidden
    %h4= t(".step_2")
    = form_tag(@bridge.new_record? ? meethue_login_usercp_bridges_path : meethue_login_usercp_bridges_path(:id => @bridge._id), :class => "form-horizontal", "data-meethue-check" => meethue_check_usercp_bridge_path(@bridge._id)) do
      - unless @bridge.new_record?
        .status
          %p
            %strong.text-success= t(".checking_meethue")

      .login{:class => !@bridge.new_record? ? :hidden : nil}
        - if @bridge.new_record?
          %p
            - if current_user.bridges.count > 1
              %span.text-error= t(".multi_meethue_account")
            - else
              %strong= t(".password_not_stored")
          %p
            %strong.text-error= t(".only_enter_meethue")

        - else
          %p
            %strong.text-error= t(".meethue_invalid_1")
          %p
            %strong= t(".meethue_invalid_2")

        .control-group
          = label_tag(:email, t(".meethue_email"), :class => "control-label")
          .controls
            = text_field_tag(:email, current_user.email, :placeholder => "john.doe@gmail.com")
            %span.help-inline

        .control-group
          = label_tag(:password, t(".meethue_password"), :class => "control-label")
          .controls
            = password_field_tag(:password)
            %span.help-inline

      %input.btn.btn-success{:type => :submit, :value => t(".save"), "data-loading-text" => t(".authenticating")}

- if current_user.bridges.count == 0
  #meethue-login.modal.hidden
    .modal-header
      %h3.text-error= t(".meethue_login_required")
    .modal-body
      %p
        %strong= t(".meethue_login_1")
      %p
        = t(".meethue_login_2")
      %p
        = t(".meethue_login_3")
      %p
        %strong.text-error= t(".meethue_login_4")
    .modal-footer
      %a.btn.pull-left{:href => "/"}= t("js.cancel")
      %a.btn.pull-right.btn-success{:href => "#", "data-dismiss" => "modal"}= t("js.ok")

#setup-portal.modal.hidden
  .modal-header
    %h3.text-error= t(".bridge_no_portal")
  .modal-body
    .setting-up
      %p= linkify_text(t(".bridge_setup_portal"), [:blank, usercp_help_meethue_path])
      %p= t(".bridge_setup_portal_2")
    .not-setup.hidden
      %p.text-error= t(".bridge_setup_not_yet")
      %p= t(".bridge_setup_not_yet_2")

    %p= linkify_text(t(".bridge_setup_portal_support"), [:email, CONFIG[:contact][:email]])
  .modal-footer
    %a.btn.pull-left{:href => "#{faq_index_path}#meethue"}= t("js.cancel")
    %a.btn.pull-right.btn-success{:href => "#", "data-loading-text" => t(".checking")}= t(".portal_setup")